# Site
name: "Simple Step"
title: "Simple Step"
description: "Take a simple step. Then plan your next one."
meta_description: "Jekyll theme for blogging."
# logo: 'assets/images/logo.png'
logo: 'assets/images/logo.svg'
logosize: 50
favicon: 'assets/images/favicon.ico'
paginate: 4
paginate_path: "/blog/page:num/"
# baseurl: '/'
baseurl: ''
email: 'stephen@simplestep.ca'
google_analytics: 'UA-46278016-1'
disqus: 'sdoxsee-github-io'
twitter: 'doxsees'
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  stephen:
    name: Stephen
    display_name: Stephen
    gravatar: 38c52c70df7bac0b26c2f691508fa54b
    email: 'stephen@simplestep.ca'
    web: https://simplestep.ca
    twitter: https://twitter.com/doxsees
    description: "Founder of Simple Step."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
        
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Other
markdown: kramdown
highlighter: rouge