# Site
name: "Simple Step Solutions"
official_name: "Simple Step Solutions"
title: "Simple Step"
description: "We help organizations build secure, extensible, and cost-effective software quickly"
meta_description: "We help organizations build secure, extensible, and cost-effective software quickly."
# logo: 'assets/images/logo.png'
logo: 'assets/images/logo.svg'
logosize: 50
favicon: 'assets/images/favicon.ico'
paginate: 4
paginate_path: "/blog/page:num/"
# baseurl: '/'
baseurl: ''
email: 'stephen@simplestep.ca'
google_analytics: 'UA-139188139-1'
disqus: 'simplestep'
twitter: 'doxsees'
include: ["_pages"]
# sharethis: '<script type="text/javascript" src="//platform-api.sharethis.com/js/sharethis.js#property=5a6b2fe4fb197a0011c589f6&product=sticky-share-buttons"></script>'

# Authors
authors:
  stephen:
    name: Stephen
    display_name: Stephen
    gravatar: 38c52c70df7bac0b26c2f691508fa54b
    web: https://simplestep.ca
    twitter: https://twitter.com/doxsees
    description: "Founder of Simple Step."

# Plugins
plugins: 
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-redirect-from

whitelist:
  - jekyll-redirect-from
          
# Archives
jekyll-archives:
  enabled:
    - tags
  layout: archive
  permalinks:
    category: '/tags/:name/'
    
# Other
markdown: kramdown
highlighter: rouge